//! Low-level FFI bindings to the Espresso C library
//!
//! This module contains the raw, unsafe bindings generated by bindgen.
//! Most users should use the safe wrappers in the parent module instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
